<a href="https://colab.research.google.com/github/mnsbharadwaj/Bigdata/blob/master/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Numpy Ranged Data
import numpy as np
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [4]:
#Numpy Arrays
arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)
print(repr(arr))
print(arr)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)
[[0. 1. 2.]
 [3. 4. 5.]]


In [6]:
arr = np.array([0, 0.1, 2])
print(arr)

[0.  0.1 2. ]


In [7]:
#copying
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [8]:
#casting : We cast NumPy arrays through their inherent astype function. 
arr = np.array([1,2,3])
float_arr = arr.astype(np.float32)
print(float_arr)


[1. 2. 3.]


In [9]:
#NAN and #INFY
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: ignored

In [10]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


OverflowError: ignored

In [11]:
#np.linespace:https://www.sharpsightlabs.com/blog/numpy-linspace/
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))


array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])


In [18]:
#Reshaping data
arr = np.array([1,2,3,4])
np.reshape(arr,(2,2))

#np.reshape(arr,(2,3)) //error
#np.reshape(arr,(1,1)) //error

array([[1, 2],
       [3, 4]])